import "@/styles/globals.css";
import {
  ClerkProvider 
} from '@clerk/nextjs'
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "@/trpc/react";


export const metadata: Metadata = {
  title: "Dionysus",
  description: "Generated by create-t3-app",
